### ISSUE TITLE
Training PyTorch on GLUE fails on my configuration

### ISSUE THREAD

**Issue by davidefiocco** [Microsoft/AzureML-BERT#1]
I am training on the CoLA and MRPC glue tasks https://github.com/Microsoft/AzureML-BERT/blob/master/PyTorch/Pretrained-BERT-GLUE.ipynb, and the trainings fail with 

> The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
02/15/2019 23:15:46 - INFO - __main__ -   Exiting context: DaskOnBatch
02/15/2019 23:15:46 - INFO - __main__ -   Exiting context: OutputCollection
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.20153117179870605 seconds
02/15/2019 23:15:47 - INFO - __main__ -   Exiting context: ProjectPythonPath
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 152, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "azureml-setup/context_manager_injector.py", line 88, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/opt/miniconda/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/miniconda/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/miniconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "run_classifier_azureml.py", line 626, in <module>
    main()
  File "run_classifier_azureml.py", line 569, in main
    lr_this_step = args.learning_rate * warmup_linear(comm.global_step/t_total, args.warmup_proportion)
AttributeError: 'DistributedCommunicator' object has no attribute 'global_step'

in `azureml-logs/80_driver_log.txt`, without running any epoch. I am using azureml-sdk with  `SDK version: 1.0.15` on a Data Science ubuntu VM, and I am not sure what the requirements are. Thanks for sharing this example!

**Comment by xiaoyongzhu** [comment]
Do you mind updating the AML SDK version first? The 1.0.15 is a bit old. 

Simply try to run this:

`pip install --upgrade azureml-sdk`

more details here:
https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py

**Comment by davidefiocco** [comment]
Thanks! I ran that command and 
`pip install --upgrade azureml-sdk[notebooks,contrib]`, and restarted the kernel but the error still is the same.
From the pypi page of the package 1.0.15 seems fairly recent https://pypi.org/project/azureml-sdk/#history (am I missing something?)

**Comment by xiaoyongzhu** [comment]
@davidefiocco sorry I misread that number... Looks like I can also repro it and might be something wrong with the runtime - I'll work with @lliimsft to solve it

**Comment by lliimsft** [comment]
@davidefiocco Thanks for pointing it out. The script [run_classifier_azureml.py](https://github.com/Microsoft/AzureML-BERT/blob/master/PyTorch/run_classifier_azureml.py) should be fixed now. Please try it out.

**Comment by davidefiocco** [comment]
Works now with the fix. Thanks!
