### ISSUE TITLE
Where is single_line_doc_file_creation.py?

### ISSUE THREAD

**Issue by inyukwo1** [microsoft/AzureML-BERT#15]
In https://github.com/microsoft/AzureML-BERT/blob/master/docs/dataprep.md,
The third step is to run "python single_line_doc_file_creation.py", but I cannot find this script.
Where can I find this script?

**Comment by skaarthik** [comment]
That step is referring to [single_line_doc_file_creation.py](https://github.com/microsoft/AzureML-BERT/blob/master/pretrain/PyTorch/dataprep/single_line_doc_file_creation.py)

**Comment by inyukwo1** [comment]
Thank you!
