### ISSUE TITLE
dataloading error

### ISSUE THREAD

**Issue by xzhu1900** [microsoft/AzureML-BERT#39]
I run into an attribute error while trying to load the bert training data:
`AttributeError: Can't get attribute 'WikiNBookCorpusPretrainingDataCreator' on <module '__main__' from 'train.py'>`

The data is retrieved from `https://bertonazuremlwestus2.blob.core.windows.net/public/bert_data.tar.gz` based on the notebook instruction ([BERT_Pretrain.ipynb](https://github.com/microsoft/AzureML-BERT/blob/master/pretrain/PyTorch/notebooks/BERT_Pretrain.ipynb))

It seems this issue is raised because WikiNBookCorpusPretrainingDataCreator class is picked into the data file upon creation but not recognized while loading it, reflecting a mismatch between the loading code and the dataset.

**Comment by skaarthik** [comment]
We will update the incorrect url in the notebook. In the meantime, use the url from https://github.com/microsoft/AzureML-BERT/blob/master/docs/artifacts.md#preprocessed-data.

**Comment by xzhu1900** [comment]
Cool. Thanks!

**Comment by skaarthik** [comment]
Fixed https://github.com/microsoft/AzureML-BERT/commit/6551791b606cf654367bd99a85cdb67f1c539415
