### ISSUE TITLE
broken dataprep link

### ISSUE THREAD

**Issue by mthielk** [microsoft/AzureML-BERT#49]
[this notebook](https://github.com/microsoft/AzureML-BERT/blob/master/pretrain/PyTorch/notebooks/BERT_Pretrain.ipynb) references [a readme](https://github.com/microsoft/AzureML-BERT/blob/master/pretrain/pytorch/dataprep/README.md) that doesn't exist.

**Comment by xiaoyongzhu** [comment]
It should already be fixed. Thanks for reporting!
