### ISSUE TITLE
How to register PyTorch BERT model, create image, and deploy as service?

### ISSUE THREAD

**Issue by davidefiocco** [microsoft/AzureML-BERT#5]
I have finetuned successfully PyTorch BERT on GLUE on an Azure cluster, and now I tried to deploy the resulting fine-tuned model as a web service. However, so far my attempts have been unsuccessful.

### Registering model
The Jupyter notebook, while having as title "Register best model" at https://github.com/microsoft/AzureML-BERT/blob/5c413cfc31c0bf829e1a791f85cff6121232e3d9/PyTorch/Pretrained-BERT-GLUE.ipynb#L478 is not actually registering a model in the Azure workspace as far as I can tell.

I tried to do so using the code
`run.register_model("fine_tuned", "outputs")`

(this should save a `pytorch_model.bin` as model in the workspace).

### Configure and create the image
After the model is registered, I need to create a Docker image. To do so, I do

     from azureml.core.model import Model
     from azureml.core.image import ContainerImage

     model = Model(ws, 'fine_tuned')

     image_config = ContainerImage.image_configuration(execution_script="score.py", 
                                                       docker_file="Dockerfile",
                                                       runtime="python", 
                                                       conda_file="myenv.yml",
                                                       dependencies=["config.json", "vocab.txt"])

    image = ContainerImage.create(name = "scorer-image",
                                   models = [model], 
                                   image_config = image_config,
                                   workspace = ws
                                   )

    image.wait_for_creation()

The code above succeeds, but the resulting image is not working when run locally and crashes with 

>    FileNotFoundError: [Errno 2] No such file or directory: 'azureml-models/fine_tuned/1/outputs/bert_config.json'

I suspect this happens because I am not uploading the `config.json` and `vocab.txt` files in the _same directory_ as the model file `pytorch_model.bin`, so that the model can't successfully load e.g. with `BertForSequenceClassification.from_pretrained`.

Does anybody have suggestions about how to handle this? Should I convert the Pytorch model to ONNX format?

**Comment by davidefiocco** [comment]
I think I figured it out, but I'll leave this open for some time so somebody can confirm this is actually the way to go.

One can register a BERT model for further use with 

```
# upload vocab and config file to model directory for later reuse
run.upload_file("outputs/vocab.txt", "my_pretrained_model/vocab.txt")
run.upload_file("outputs/bert_config.json", "my_pretrained_model/bert_config.json")
```

to the current `run`, and then register the model with 

```
# register model
run.register_model("fine_tuned", "outputs")

```

This should allow easier reuse of the model in the image creation and deployment.

**Comment by Darek-S** [comment]
Could you please show what does your "score.py" file look like (since it is not included in this project)? Thanks.

**Comment by davidefiocco** [comment]
@Darek-S coming up with a working solution for deployment requires a bit of refactoring (it would be great if the Azure devs would share something, I may try to fork this repo to share something viable).

In broad strokes, to deploy a service I think that one could start from the `score.py` examples provided in the [Azure documentation](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-deploy-and-where#script), and in particular for [Pytorch](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/pytorch_score.py).

To write the `init()` function, one could then borrow code from the HuggingFace repo (https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_classifier.py) 
and in particular the model initialization from a folder bits using code along the lines of 

    processor = MyFavoriteGLUEProcessor()
    
    model_path = Model.get_model_path('my_model_name_in_the_azureml_workspace')
  
    model = BertForSequenceClassification.from_pretrained(model_path,
              cache_dir=None,
              num_labels=num_labels)

    tokenizer = BertTokenizer.from_pretrained(model_path, do_lower_case=True)

To write the `run()` function, one could again borrow from HuggingFace the bits relevant for inference (in particular the creation of `eval_dataloader`, `logits` etc.) and return the softmax of the logits in the `result`.

Hope this helps!

**Comment by aribornstein** [comment]
Darek-S I just submitted an example of this for BERT NER when it gets merged you can use it as reference.
